=head1 ABOUT

This is 'Niecza', which will eventually be a Perl 6 implementation focusing
on optimization research.  It targets the Common Language Runtime (ECMA-335;
implementations are "Mono" and ".NET").

To see the current state of the art, the best documentation is the testsuite,
C<test.pl>.

=head1 DEPENDENCIES (RUNTIME)

=over 4

=item *

To run on Mono:  2.6.4 and later are well-tested, though success has been
reported with 2.4.x as well.  ggoebel on #perl6 reports that 2.6.7 fails
with a bus error on OS X 10.4 x86, but 2.6.4 works; 2.6.7 is fine on other
platforms.  2.9.x or later is recommended for best performance.

Debian and derivatives have a modular mono packaging; you should install
'mono-complete'.  (The other packages exist for the sake of Debian-packaged
programs.)

=item *

To run on Windows/Microsoft .NET 3.5 (2.0 runtime with 3.5 extensions)
or .NET 4.0: C<http://goo.gl/PMKvB>

Currently, you need to make a change to the C<Makefile> to enable
a successful build under Cygwin, but once sorear makes a C<Configure.pl> and/or
uses the mono autotools templates, this won't be needed... merely remove C<mono>
from the line starting with C<RUN_CLR=>.  Niecza also runs on mono/Windows.

=back

=head1 DEPENDENCIES (BUILD FROM SOURCE)

=over 4

=item *

wget (to fetch a bootstrapping binary).

=item *

GNU make

=item *

unzip

=back

=head1 USING

    $ make
    ... snip build spam ...
    $ mono run/Niecza.exe
    niecza> say 2 + 2
    4
    niecza> ^D
    $ mono run/Niecza.exe -e 'say 2 + 2'
    4
    $

=head1 COPYRIGHT AND LICENSE

Niecza is Copyright 2010 Stefan O'Rear et al.  It may be used and distributed
under the Artistic License 2.0 (included under LICENSE).

=head1 CREDITS AND PRIOR ART

This project was originally a spin-off of experiments done for
Matthew "diakopter" Wilson's sprixel project, and is heavily inspired by
many of its lower-level details.
