=head1 ABOUT

This is 'Niecza', which will eventually be a Perl 6 implementation focusing
on optimization research.  It targets the Common Language Runtime (ECMA-335;
implementations are "Mono" and ".NET").

To see the current state of the art, the best documentation is the testsuite,
C<test.pl>.

=head1 DEPENDENCIES

=over 4

=item *

Mono.  2.6.4 and later are well-tested, though success has been reported with 2.4.x as well.  ggoebel on #perl6 reports that 2.6.7 fails with a bus error on OS X 10.4 x86, but 2.6.4 works; 2.6.7 is fine on other platforms.

Debian and derivatives have a modular mono packaging; you should install
'mono-complete'.  (The other packages exist for the sake of Debian-packaged
programs.)

=item *

Perl 5.10.1 (or 5.10.0 with autodie installed from CPAN) in your PATH

=item *

Moose, Sub::Exporter, File::Slurp, Term::ReadLine, IPC::System::Simple,
JSON, STD, File::ShareDir, and YAML::XS from CPAN

=back

=head1 USING

    $ xbuild
    ... snip build spam ...
    $ ./niecza_eval
    > say 2 + 2
    4
    > ^D
    $ ./niecza_eval -e 'say 2 + 2'
    4
    $

=head1 COPYRIGHT AND LICENSE

Niecza is Copyright 2010 Stefan O'Rear et al.  It may be used and distributed
under the Artistic License 2.0 (included under LICENSE).

=head1 CREDITS AND PRIOR ART

This project is a spin-off of experiments done for Matthew "diakopter" Wilson's
csmeta / Sprixel project, and is heavily inspired by many of its lower-level
details.
