#!/bin/sh
prove -e 't/fudgeandrun' \
    ../roast/integration/lexical-array-in-inner-block.t \
    ../roast/S02-builtin_data_types/array.t \
    ../roast/S02-builtin_data_types/autovivification.t \
    ../roast/S02-builtin_data_types/bool.t \
    ../roast/S02-builtin_data_types/parsing-bool.t \
    ../roast/S02-lexical-conventions/unicode.t \
    ../roast/S02-names_and_variables/contextual.t \
    ../roast/S02-whitespace_and_comments/begin_end_pod.t \
    ../roast/S02-whitespace_and_comments/pod-in-multi-line-exprs.t \
    ../roast/S03-metaops/reduce.t \
    ../roast/S03-operators/assign-is-not-binding.t \
    ../roast/S03-operators/binding-scalars.t \
    ../roast/S03-operators/bit.t \
    ../roast/S03-operators/chained-declarators.t \
    ../roast/S03-operators/relational.t \
    ../roast/S03-operators/scalar-assign.t \
    ../roast/S03-operators/spaceship-and-containers.t \
    ../roast/S03-smartmatch/any-bool.t \
    ../roast/S03-smartmatch/any-str.t \
    ../roast/S04-declarations/state.t \
    ../roast/S04-statement-modifiers/for.t \
    ../roast/S04-statement-modifiers/given.t \
    ../roast/S04-statement-modifiers/if.t \
    ../roast/S04-statement-modifiers/unless.t 
    ../roast/S04-statements/for_with_only_one_item.t \
    ../roast/S04-statements/gather.t \
    ../roast/S04-statements/if.t \
    ../roast/S04-statements/last.t \
    ../roast/S04-statements/map-and-sort-in-for.t \
    ../roast/S04-statements/next.t \
    ../roast/S04-statements/no-implicit-block.t \
    ../roast/S04-statements/until.t \
    ../roast/S04-statements/while.t \
    ../roast/S05-grammar/protoregex.t \
    ../roast/S06-traits/is-rw.t \
    ../roast/S09-autovivification/autoincrement.t \
    ../roast/S12-class/inheritance-class-methods.t \
    ../roast/S29-any/cmp.t \
    ../roast/S32-num/power.t \
    ../roast/S32-str/append.t \

