#!/bin/sh
prove -e 't/fudgeandrun' \
    ../roast/S02-builtin_data_types/array.t \
    ../roast/S02-builtin_data_types/autovivification.t \
    ../roast/S02-builtin_data_types/bool.t \
    ../roast/S02-lexical-conventions/unicode.t \
    ../roast/S02-whitespace_and_comments/begin_end_pod.t \
    ../roast/S02-builtin_data_types/parsing-bool.t \
    ../roast/S02-whitespace_and_comments/pod-in-multi-line-exprs.t \
    ../roast/S03-operators/scalar-assign.t \
    ../roast/S03-operators/spaceship-and-containers.t \
    ../roast/S03-operators/assign-is-not-binding.t \
    ../roast/S03-operators/relational.t \
    ../roast/S04-statements/if.t \
    ../roast/S04-statement-modifiers/unless.t \
    ../roast/S04-statements/if.t \
    ../roast/S04-statements/map-and-sort-in-for.t \
    ../roast/S04-statements/until.t \
    ../roast/S06-traits/is-rw.t \
    ../roast/S09-autovivification/autoincrement.t \
    ../roast/S12-class/inheritance-class-methods.t \
    ../roast/S29-any/cmp.t \
    ../roast/S32-str/append.t \
    ../roast/S32-num/power.t \
    ../roast/integration/lexical-array-in-inner-block.t \
